### PR TITLE
Fix key comparision

### LINKED ISSUE #61: Quoted keys should not be different from bare keys
After asking on the Toml project [issue #733](https://github.com/toml-lang/toml/issues/733), I can now confirm that quoted keys and bare keys with the same string are the same semantic key. 

This means that the current implementation of [TomlType.Table.Key.compare] is wrong with regard to the Toml specification because it always separate bare and quoted keys.

### PR DESCRIPTION
**Pull request by seliopou**
Treat quoted and bare keys the same with respect to comparison.

Closes #61.

### CODE REVIEW

**Comment by zapashcanon** [comment]
@seliopou are you still interested in this ? If yes, could you rebase the PR so I can review it and merge it ?

**Comment by seliopou** [comment]
I don't need these changes any more, but I'm happy to rebase if it's not too much effort.

File: tests/key_test.ml [hunk 1]
```diff
@@ -4,13 +4,21 @@ open Utils
 let test_bad_bk k () =
   assert_raises (Toml.Types.Table.Key.Bad_key k) (fun () -> Toml.Min.key k)
 
+let quoted_bare_comparsion () =
```
Comment (zapashcanon) [inline tests/key_test.ml:7]:
```suggestion
let quoted_bare_comparison () =
```

File: tests/key_test.ml [hunk 2]
```diff
@@ -4,13 +4,21 @@ open Utils
...
+;;
+
 let suite =
   "Printing values"
   >::: [ ( "good key" >:: fun () ->
            test_string "\"my_good_unicodé_key\""
              (Toml.Types.Table.Key.to_string
                 (Toml.Types.Table.Key.quoted_key_of_string
                    "my_good_unicodé_key")) )
+       ; "quoted vs bare" >:: quoted_bare_comparsion
```
Comment (zapashcanon) [inline tests/key_test.ml:21]:
```suggestion
       ; "quoted vs bare" >:: quoted_bare_comparison
```

**Comment by zapashcanon** [comment]
Thanks ! Apart from the minor typo `comparsion` -> `comparison` that looks good to me.

**Comment by zapashcanon** [comment]
Thanks !
